<a href="https://colab.research.google.com/github/mint-rin/SeSAC/blob/main/02_word_representation_TDM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TDM 직접 구현

In [2]:
docs = ['동물원 코끼리',
        '동물원 원숭이 바나나',
        '엄마 코끼리 아기 코끼리',
        '원숭이 바나나 코끼리 바나나']

## 1. 토큰화: 공백으로 토큰화 진행

In [3]:
doc_ls = []

for doc in docs:
  doc_ls.append(doc.split(' '))
doc_ls

# for문을 한 줄로 쓰는 경우: doc_ls = [doc.split() for doc in docs]

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

## 2. 유니크한 토큰 사전 구하기

## 2-1 빈 딕셔너리 생성

In [4]:
from collections import defaultdict

word2id = defaultdict(lambda: len(word2id))

for doc in doc_ls:
    for token in doc:
        word2id[token]

word2id

# 이중 for문을 한 줄로 쓰기
# word2id[token] for doc in doc_ls for token in doc

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

### 2-2 위에서 생성한 빈 딕셔너리에 유니크한 토큰 넣기

In [5]:
for doc in doc_ls:
  for tokein in doc:
    word2id[token]
    print(token)
    print('\t',word2id)

word2id

# 위의 for문을 한 줄로 쓰는 경우: word2id[token] for doc in doc_ls for token in doc

바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})
바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})
바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})
바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})
바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})
바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})
바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})
바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})
바나나
	 defaultdict(<function <lambda> at 0x7a3731651240>, {'동물원':

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

## BoW 구하기

In [6]:
import numpy as np

# 0으로 채운 행렬 만들기
TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)

for i, doc in enumerate(doc_ls):
  for token in doc:
    TDM[word2id[token]] += 1  # 해당 토큰의 위치(column)

# 행렬로 표기(BoW와 차이점: BoW는 1차원 배열)
TDM

array([[2, 2, 2, 2],
       [4, 4, 4, 4],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
import pandas as pd

doc_names = ['문서' + str(i) for i in range(len(doc_ls))]

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
df_TDM = pd.DataFrame(TDM, columns = doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    2    2    2    2
코끼리    4    4    4    4
원숭이    2    2    2    2
바나나    3    3    3    3
엄마     1    1    1    1
아기     1    1    1    1

# sklearn 라이브러리 쓰기

In [15]:
docs = ['동물원 코끼리',
        '동물원 원숭이 바나나',
        '엄마 코끼리 아기 코끼리',
        '원숭이 바나나 코끼리 바나나']

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

# sklearn은 DTM으로 만들어지게 설정되어 있음
count_vect = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 2],
       [0, 2, 0, 0, 1, 1]])

In [17]:
# TDM
DTM.toarray().T

array([[1, 1, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 2, 1]])

In [18]:
import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = count_vect.get_feature_names_out()
df_TDM = pd.DataFrame(DTM.toarray().T, columns = doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
바나나    0    1    0    2
아기     0    0    1    0
엄마     0    0    1    0
원숭이    0    1    0    1
코끼리    1    0    2    1