<a href="https://colab.research.google.com/github/mint-rin/SeSAC/blob/main/word_representation_3_TF_IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TF-IDF 직접 구현

In [ ]:
# docs = documents
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

## 토큰화
- 각 토큰(단어)을 그대로 사용할 수 없기 때문에 토큰에 index 부여
- 공백으로 토큰화 진행




In [ ]:
# 빈 리스트 생성
doc_ls = []

# 공백으로 나눠서 리스트 안에 넣기
for doc in docs:
  doc_ls.append(doc.split())
doc_ls

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

## 유니크한 토큰 사전 구하기

### 2-1. 빈 딕셔너리 생성

In [ ]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
word2id

defaultdict(<function __main__.<lambda>()>, {})

### 2-2. 위에서 생성한 빈 딕셔너리에 유니크한 토큰 넣기

In [ ]:
for doc in doc_ls:
  for token in doc:
    word2id[token]
    print(token)
    print('\t', word2id)

word2id

오늘
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0})
동물원에서
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0, '동물원에서': 1})
원숭이와
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2})
코끼리를
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3})
봤어
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4})
동물원에서
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4})
원숭이에게
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5})
바나나를
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5, '바나나를': 6})
줬어
	 defaultdict(<function <lambda> at 0x7b59bf74d240>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5, '바나나를': 6, '줬어': 7})
바나나를
	 defaultdict(<function <l

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이와': 2,
             '코끼리를': 3,
             '봤어': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

## TF 계산
TF = (특정 단어 등장 빈도)/(문서 내 전체 등장 단어 빈도)

In [ ]:
import numpy as np

TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)

for i, doc in enumerate(doc_ls):
  print(doc)
  for token in doc:
    TDM[word2id[token], i] += 1   # 해당 토큰의 위치(column)
    print(token)
    print(TDM)
    print('\t')

['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어']
오늘
[[1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
동물원에서
[[1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
원숭이와
[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
코끼리를
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
봤어
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]]
	
['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']
동물원에서
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]]
	
원숭이에게
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]]
	
바나나를
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]
	
줬어
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
	
바나나를
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 2]
 [0 1]]
	


In [ ]:
# TF = (특정 단어 등장 빈도) / (문서 내 전체 등장 단어 빈도)
def computeTF(TDM):
  doc_len = len(docs)   # 문서 개수 2개
  word_len = len(word2id)
  print('문서 수 : ', doc_len)
  print('전체 단어 수 : ', word_len)

  tf = np.zeros((word_len, doc_len))
  print(tf)

  for doc_i in range(len(doc_ls)):
    print(docs[doc_i])
    for word_i in range(len(word2id)):
      tf[word_i, doc_i] = TDM[word_i, doc_i]/TDM[:, doc_i].sum()
    print(tf)
  return tf

In [ ]:
tf = computeTF(TDM)

문서 수 :  2
전체 단어 수 :  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]


In [ ]:
tf

array([[0.2, 0. ],
       [0.2, 0.2],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0. , 0.2],
       [0. , 0.4],
       [0. , 0.2]])

## IDF 계산하기
IDF = -log(단어가 등장한 문서 수/총 문서 수)

In [ ]:
import math

# IDF 계산 = -log(단어가 등장한 문서 수 / 총 문서 수)
def computeIDF(TDM):
  doc_len = len(docs)   # 문서 개수 2개
  word_len = len(word2id)
  print('문서 수 : ', doc_len)
  print('전체 단어 수 : ', word_len)

  idf = np.zeros(word_len)
  print(idf)

  for doc_i in range(len(doc_ls)):
    for word_i in range(len(word2id)):
      idf[word_i] = -math.log10(np.count_nonzero(TDM[word_i,:])/doc_len)
    print(idf)
    return idf

In [ ]:
idf = computeIDF(TDM)
idf

문서 수 :  2
전체 단어 수 :  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]


array([ 0.30103, -0.     ,  0.30103,  0.30103,  0.30103,  0.30103,
        0.30103,  0.30103])

## TF-IDF 계산하기

In [ ]:
# TF-IDF 곱
def computeTFIDF(TDM):
  tf = computeTF(TDM)
  idf = computeIDF(TDM).T
  tfidf = np.zeros(tf.shape)

  for doc_i in range(len(doc_ls)):
    print(docs[doc_i])
    for word_i in range(len(word2id)):
      tfidf[word_i, doc_i] = tf[word_i, doc_i] * idf[word_i]

  print('TF-IDF 최종')
  print(tfidf)
  return tfidf

In [ ]:
tfidf = computeTFIDF(TDM)

문서 수 :  2
전체 단어 수 :  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]
문서 수 :  2
전체 단어 수 :  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]
오늘 동물원에서 원숭이와 코끼리를 봤어
동물원에서 원숭이에게 바나나를 줬어 바나나를
TF-IDF 최종
[[ 0.060206  0.      ]
 [-0.       -0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.        0.060206]
 [ 0.        0.120412]
 [ 0.        0.060206]]


In [ ]:
tfidf

array([[ 0.060206,  0.      ],
       [-0.      , -0.      ],
       [ 0.060206,  0.      ],
       [ 0.060206,  0.      ],
       [ 0.060206,  0.      ],
       [ 0.      ,  0.060206],
       [ 0.      ,  0.120412],
       [ 0.      ,  0.060206]])

## 시각화로 확인

In [ ]:
import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
print('vocab : ', vocab)
tfidf = computeTFIDF(TDM)
pd.DataFrame(tfidf.T, columns=vocab)

vocab :  ['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어', '원숭이에게', '바나나를', '줬어']
문서 수 :  2
전체 단어 수 :  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]
문서 수 :  2
전체 단어 수 :  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]
오늘 동물원에서 원숭이와 코끼리를 봤어
동물원에서 원숭이에게 바나나를 줬어 바나나를
TF-IDF 최종
[[ 0.060206  0.      ]
 [-0.       -0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.        0.060206]
 [ 0.        0.120412]
 [ 0.        0.060206]]


오늘  동물원에서      원숭이와      코끼리를        봤어     원숭이에게      바나나를        줬어
0  0.060206   -0.0  0.060206  0.060206  0.060206  0.000000  0.000000  0.000000
1  0.000000   -0.0  0.000000  0.000000  0.000000  0.060206  0.120412  0.060206

# sklearn 라이브러리 사용

In [ ]:
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
        '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidv = TfidfVectorizer()
tfidv = TfidfVectorizer()
tfidv = tfidv.fit(docs)
tfidv.transform(docs).toarray()
vocab = tfidv.get_feature_names_out()

In [ ]:
import pandas as pd
df = pd.DataFrame(tfidv.transform(docs).toarray(), columns = vocab)
df

동물원에서      바나나를        봤어        오늘     원숭이에게      원숭이와        줬어  \
0  0.335176  0.000000  0.471078  0.471078  0.000000  0.471078  0.000000   
1  0.278943  0.784088  0.000000  0.000000  0.392044  0.000000  0.392044   

       코끼리를  
0  0.471078  
1  0.000000